# Generated by Django 6.1.1 on 2026-10-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(db_index=True, max_length=10)),
                ('rack_id', models.IntegerField(blank=True, null=True)),
                ('retail_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('latitude', models.FloatField(blank=True, db_index=True, null=True)),
                ('longitude', models.FloatField(blank=True, db_index=True, null=True)),
                ('geocoded', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'db_table': 'fuel_stations',
                'indexes': [models.Index(fields=['state', 'geocoded'], name='fuel_statio_state_d61f05_idx'), models.Index(fields=['latitude', 'longitude'], name='fuel_statio_latitud_c84538_idx')],
            },
        ),
    ]
